package puzzle;

/*
* Generated by the IBM IDL-to-Java compiler, version 1.0
* from F:\TestRoot\apps\a1\units\include\PolicyHome.idl
* Wednesday, June 17, 1998 6:44:40 o 'clock AM GMT+00:00
* */
// 컴파일러는 주석에 있는 u를 유니코드 이스케이프 시퀀스로 인식하고 파싱한다.
// 시퀀스 뒤로는 16진수가 와야하지만 그렇지 않기에 오류를 발생시킨다.
public class Puzzle15 {
    public static void main(String[] args) {
        System.out.print("Hell");
        System.out.println("o world");

    }
}
